### ISSUE TITLE
Multiple onCreate listeners act on the target of the first listener

### ISSUE THREAD

**Issue by eclecto** [eclecto/jQuery-onMutate#17]
Example:

    $.onCreate('#element1', callback1);
    $.onCreate('#element2', callback2);

Both callbacks will execute only on `#element1`.

**Comment by chocolateboy** [comment]
jQuery-onMutate: 1.4.2
Browser: Firefox 49.0.1
jQuery: 3.1.1
OS: Linux (Arch)
 
I'm still seeing this with 1.4.2. i.e.

```html
<html>
    <body>
        <a id="foo">Foo</a>
        <a id="bar">Bar</a>
    </body>
<html>
```

```javascript
function debug ($link) {
    console.warn('created:', $link.attr('id'))
}

$('body').onCreate('a#foo', debug);
$('body').onCreate('a#bar', debug);
```

outputs:

    created: foo
    created: foo
